# Generated by Django 3.0.5 on 2021-11-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20211117_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_ended',
            new_name='date_added',
        ),
    ]
